---
- name: Import Elasticsearch public GPG key into rpm
  rpm_key: state=present key=http://packages.elastic.co/GPG-KEY-elasticsearch

- name: Copying yum repo for Elasticsearch
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: Install Elasticsearch
  yum: name=elasticsearch state=installed

- name: Start elasticsearch
  service: name=elasticsearch enabled=yes state=started
